name = "database-tools"
title = "MongoDB Database Tools"

intersphinx = [ "https://docs.mongodb.com/manual/objects.inv", 
                "https://docs.atlas.mongodb.com/objects.inv", 
                "https://docs.mongodb.com/compass/current/objects.inv"]

toc_landing_pages = ["/installation/installation"]

[constants]
dbtools = "MongoDB Database Tools"
dbtools-short = "Database Tools"
dbtools-pkg = "mongodb-database-tools"
package-name-org = "mongodb-org"
package-name-enterprise = "mongodb-enterprise"
version = "100.2.1"
release = "{+version+}"
pgp-version = "{+version+}"
pgp-fingerprint = "E162F504A20CDF15827F718D4B7C549A058F8B6B"
rsa-key = "4B7C549A058F8B6B"
pgp-fingerprint-fmt = "E162 F504 A20C DF15 827F  718D 4B7C 549A 058F 8B6B"
windows-sha256 = "AF5AF79EFE540DCDDC2825A396C71FCFC4FEB463BC9CADDCCDE20AD126321CCC"
pgp-short-fingerprint = "0x4B7C549A058F8B6B"
source-available = "`source available and free to use <https://github.com/mongodb/mongo/>`_"

[manpages.bsondump]
file = "bsondump.txt"
title = "bsondump"
section = 1

[manpages.mongodump]
file = "mongodump.txt"
title = "mongodump"
section = 1

[manpages.mongoexport]
file = "mongoexport.txt"
title = "mongoexport"
section = 1

[manpages.mongofiles]
file = "mongofiles.txt"
title = "mongofiles"
section = 1

[manpages.mongoimport]
file = "mongoimport.txt"
title = "mongoimport"
section = 1

[manpages.mongorestore]
file = "mongorestore.txt"
title = "mongorestore"
section = 1

[manpages.mongostat]
file = "mongostat.txt"
title = "mongostat"
section = 1

[manpages.mongotop]
file = "mongotop.txt"
title = "mongotop"
section = 1
