name: mongodb
url: https://docs.mongodb.com/manual/
path: mongodb.inv
---
name: python
url: https://docs.python.org/2/
path: python2.inv
---
name: python2
url: https://docs.python.org/2/
path: python2.inv
---
name: python3
url: https://docs.python.org/3/
path: python3.inv
---
name: clouddocs
url: https://docs.atlas.mongodb.com/
path: cloud-docs.inv
---
name: compassdocs
url: https://docs.mongodb.com/compass/current/
path: compass-docs.inv
...
